version: 2.1

orbs:
  win: circleci/windows@2.4.0

defaults: &defaults
  parameters:
    node_version:
      type: string
      default: ""
    go_version:
      type: string
      default: ""
  working_directory: ~/snyk-go-plugin

windows_defaults: &windows_defaults
  environment:
    npm_config_loglevel: silent
  executor:
    name: win/default

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install
  install_node_npm:
    description: Install correct Node version
    parameters:
      node_version:
        type: string
        default: ""
    steps:
      - run:
          name: Install correct version of Node
          command: nvm install << parameters.node_version >>
      - run:
          name: Use correct version of Node
          command: nvm use << parameters.node_version >>
  show_node_version:
    description: Log Node and npm version
    steps:
      - run:
          name: Node version
          command: node --version
      - run:
          name: NPM version
          command: npm --version
  install_gvm_unix:
    steps:
      - run:
          name: Install GVM
          command: |
              bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer) ; fi
              source $HOME/.gvm/scripts/gvm; gvm install go${GO_VERSION} --binary
  install_go_unix:
    description: Install Go
    parameters:
      go_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing Go
          command: gvm install go<< parameters.go_version >>
  show_go_version:
    description: Log Go and gvm version
    steps:
      - run:
          name: Go version
          command: go --version
      - run:
          name: GVM version
          command: gvm --version
  install_go_windows:
    description: Install Go
    parameters:
      go_version:
        type: string
        default: ""
    steps:
      - run:
          name: Installing Go
          command: choco install golang --version << parameters.go_version >>

jobs:
  lint:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - show_node_version
      - run:
          name: Run lint
          command: npm run lint

  test-windows:
    <<: *defaults
    <<: *windows_defaults
    environment:
      Go: << parameters.go_version >>
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - install_node_npm:
          node_version: << parameters.node_version >>
      - install_go_windows:
          go_version: << parameters.go_version >>
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  test-unix:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    environment:
      GO_VERSION: << parameters.go_version >>
    steps:
      - checkout
      - install_gvm_unix:
      - show_go_version
      - install_go_unix:
          go_version: << parameters.go_version >>
      - install_deps
      - show_node_version
      - run:
          name: Run tests
          command: npm test

  release:
    <<: *defaults
    docker:
      - image: circleci/node:<< parameters.node_version >>
    environment:
      NODE_ENV: "production"
    resource_class: small
    steps:
      - checkout
      - install_deps
      - run:
          name: Publish to GitHub
          command: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
    - lint:
        name: Lint
        context: nodejs-install
        node_version: "10"
        filters:
          branches:
            ignore:
              - master

    # UNIX tests
    - test-unix:
        name: Unix Tests for Go=1.10.8 Node=8
        context: nodejs-install
        go_version: "1.10.8"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.10.8 Node=10
        context: nodejs-install
        go_version: "1.10.8"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.10.8 Node=12
        context: nodejs-install
        go_version: "1.10.8"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.13.3 Node=8
        context: nodejs-install
        go_version: "1.13.3"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.13.3 Node=10
        context: nodejs-install
        go_version: "1.13.3"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.13.3 Node=12
        context: nodejs-install
        go_version: "1.13.3"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.14.0 Node=8
        context: nodejs-install
        go_version: "1.14.0"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.14.0 Node=10
        context: nodejs-install
        go_version: "1.14.0"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-unix:
        name: Unix Tests for Go=1.14.0 Node=12
        context: nodejs-install
        go_version: "1.14.0"
        node_version: "8"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master

    # Windows
    - test-windows:
        name: Windows Tests for Go=8 Node=8
        context: nodejs-install
        go_version: "1.10.8"
        node_version: "8.17.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=8 Node=10
        context: nodejs-install
        go_version: "1.10.8"
        node_version: "10.21.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=8 Node=12
        context: nodejs-install
        go_version: "1.10.8"
        node_version: "12.0.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=1.13.3 Node=8
        context: nodejs-install
        go_version: "1.13.3"
        node_version: "8.17.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=1.13.3 Node=10
        context: nodejs-install
        go_version: "1.13.3"
        node_version: "10.21.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=1.13.3 Node=12
        context: nodejs-install
        go_version: "1.13.3"
        node_version: "12.0.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=1.14.0 Node=8
        context: nodejs-install
        go_version: "1.14.0"
        node_version: "8.17.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=1.14.0 Node=10
        context: nodejs-install
        go_version: "1.14.0"
        node_version: "10.21.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master
    - test-windows:
        name: Windows Tests for Go=1.14.0 Node=12
        context: nodejs-install
        go_version: "1.14.0"
        node_version: "12.0.0"
        requires:
          - Lint
        filters:
          branches:
            ignore:
              - master

    # Release
    - release:
        name: Release
        context: nodejs-app-release
        node_version: "10"
        filters:
          branches:
            only:
              - master
